### ISSUE TITLE
Function Call throwing error on SemCheck

### ISSUE THREAD

**Issue by ranji2612** [saniaarif22/PlOtter#21]
Ensure that the function calls dont throw errors on semcheck

fn addOne():
    num a
    a = 3
end

addOne()
num a
a = 5
a = a*5

> errors out at the addOne function call

**Comment by saniaarif22** [comment]
In the function def, addOne should take a param right? Like addOne(num x)

**Comment by ranji2612** [comment]
check now

**Comment by ranji2612** [comment]
Fixed with 2aa90e44f7e7597cad273ff3be78cfc2da89ed2d
